apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: base-env-pod-read
  namespace: base-env
subjects:
- kind: ServiceAccount
  name: jack
  namespace: base-env
roleRef:
  kind: ClusterRole
  name: pods-read-all
  apiGroup: rbac.authorization.k8s.io 
