apiVersion: v1
kind: Service
metadata:
    name: mysql-baseenv
    namespace: base-env
spec:
    ports:
        - protocol: TCP
          port: 3306
          targetPort: 3306

---
apiVersion: v1
kind: Endpoints
metadata:
    name: mysql-baseenv
    namespace: base-env
subsets:
    - addresses:
        - ip: 172.17.1.26
      ports:
        - port: 3306
