apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deploy
  namespace: base-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      name: rabbitmq
      namespace: base-env
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: harbor.sys.bandubanxie.com/yunshuxie/service/rabbitmq:v2
        imagePullPolicy: IfNotPresent
        ports:
        - name: manageport
          containerPort: 15672
          protocol: TCP
        - name: clientport
          containerPort: 5672
        - name: serverinport
          containerPort: 25672
      imagePullSecrets:
      - name: registry-secret 
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
        - 10.111.250.201
        options:
        - name: ndots
          value: "2"
        - name: edns0
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc
  namespace: base-env
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
  - name: rabbitmq-svc-manageport
    port:  15672
    targetPort: 15672
  - name: rabbitmq-svc-clientport
    port: 5672
    targetPort: 5672
  - name: rabbitmq-svc-serverinport
    port: 25672
    targetPort: 25672
