apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
  namespace: base-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      name: redis
      namespace: base-env
      labels:
        app: redis
    spec:
      
      containers:
      - name: redis
        image: harbor.sys.bandubanxie.com/yunshuxie/service/redis:v4.0
        imagePullPolicy: IfNotPresent
        command: ["redis-server"]
        args:
        - --requirepass "yunshuxie1029Password"
        ports:
        - name: redis-port
          containerPort: 6379
          protocol: TCP
      imagePullSecrets:
      - name: registry-secret 
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
        - 10.111.250.201
        options:
        - name: ndots
          value: "2"
        - name: edns0
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: base-env
spec:
  selector:
    app: redis
  type: NodePort
  ports:
  - name: redis-svc-port
    port: 6379 
    targetPort: 6379
