apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketmq-deploy
  namespace: base-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq
  template:
    metadata:
      name: rocketmq
      namespace: base-env
      labels:
        app: rocketmq
    spec:
      containers:
      - name: rocketmq
        image: harbor.sys.bandubanxie.com/yunshuxie/service/rocketmq:v1
        imagePullPolicy: IfNotPresent
        ports:
        - name: nameserverport
          containerPort: 9876
          protocol: TCP
        - name: brokerport
          containerPort: 10911
      imagePullSecrets:
      - name: registry-secret 
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
        - 10.111.250.201
        options:
        - name: ndots
          value: "2"
        - name: edns0
---
apiVersion: v1
kind: Service
metadata:
  name: rocket-svc
  namespace: base-env
spec:
  type: NodePort
  selector:
    app: rocketmq
  ports:
  - name: rocketmq-svc-nameserver
    port:  9876
    targetPort: 9876
  - name: rocketmq-svc-broker
    port: 10911
    targetPort: 10911
