apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: coredns
  namespace: {{ .Values.namespace }}
  labels:
    app: coredns
spec:
  replicas: 1
  serviceName: coredns
  updateStrategy:
    type: RollingUpdate
  #podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: coredns
  template:
    metadata:
      labels:
        app: coredns
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: coredns
        image: harbor.sys.bandubanxie.com/yunshuxie/service/coredns:1.6.7
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 53
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 53
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 53
          initialDelaySeconds: 15
          periodSeconds: 5
        resources:
          limits:
            memory: 1048Mi
          requests:
            memory: 536Mi
        volumeMounts:
        - name: coredns
          mountPath: /home/service/coredns/conf/
      restartPolicy: Always
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
        - 10.96.0.10
        options:
        - name: ndots
          value: "2"
        - name: edns0
      volumes:
      - name: coredns
        configMap:
          name: coredns-configmap
          items:
          - key: Corefile
            path: Corefile
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-configmap
  namespace: {{ .Values.namespace }}
data:
  Corefile: |
    svc.cluster.local {
        forward . 10.96.0.10
    }

    . {
        hosts {
                fallthrough
        }
        forward . 192.168.12.200
        reload
        log
    }
---

apiVersion: v1
kind: Service
metadata:
  name: coredns
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: coredns
  ports:
  - name: udp
    protocol: UDP
    port: 53
    targetPort: 53
---
apiVersion: v1
kind: Service
metadata:
  name: webproc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: coredns
  ports:
  - name: webproc
    port: 80
    targetPort: 8080
  type: NodePort
