apiVersion: v1
kind: Pod
metadata:
  name: utils-cli-pod
  namespace: base-env
spec:
  containers:
  - name: utils-cli
    image: harbor.sys..com/yunshuxie/utils/utils-image:v3
    imagePullPolicy: IfNotPresent
    command: ["/bin/bash","-ce","tail -f /dev/null"]
  imagePullSecrets:
  - name: registry-secret
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
    - 10.111.250.201
    options:
    - name: ndots
      value: "2"
    - name: edns0
