apiVersion: v1
data:
  kibana.yml: |
    server.name: kibana
    server.host: "0"
    elasticsearch.hosts: [ "http://es.log-mon.svc.cluster.local:9200" ]
    xpack.monitoring.ui.container.elasticsearch.enabled: true
    elasticsearch.requestTimeout: 300000
    elasticsearch.username: "elastic"
    elasticsearch.password: "121109"
kind: ConfigMap
metadata:
  namespace: log-mon
  creationTimestamp: null
  name: kibana.yml
