apiVersion: v1
data:
  elasticsearch.yml: |
    cluster.name: "docker-cluster"
    network.host: 0.0.0.0
    http.port: 9200
    node.name: node-1
    xpack.security.enabled: true
    cluster.initial_master_nodes: ["node-1"]
    bootstrap.system_call_filter: false
    bootstrap.memory_lock: false
    xpack.security.transport.ssl.enabled: true
    xpack:
      security:
        authc:
          realms:
            ldap:
              ldap1:
                #type: "ldap"
                order: 1
                url: "ldap://192.168.12.137:389"
                bind_dn: "cn=root,dc=yunshuxie,dc=com"
                bind_password: yifei950426
                user_dn_templates:
                  - "cn={0},ou=People,dc=yunshuxie,dc=com"
                group_search:
                  base_dn: "dc=yunshuxie,dc=com"
                files:
                  role_mapping: "/usr/share/elasticsearch/config/role_mapping.yml"
                unmapped_groups_as_roles: false
  role_mapping.yml: |
    # Role mapping configuration file which has elasticsearch roles as keys
    # that map to one or more user or group distinguished names
    log_reader:
      - "cn=liangyawang,ou=people,dc=yunshuxie,dc=com"
      - "cn=quke,ou=people,dc=yunshuxie,dc=com"
      - "cn=wanghongwei,ou=people,dc=yunshuxie,dc=com"
    #roleA:   this is an elasticsearch role
    #  - groupA-DN  this is a group distinguished name
    #  - groupB-DN
    #  - user1-DN   this is the full user distinguished name

    #power_user:
    #  - "cn=admins,dc=example,dc=com"
    #user:
    #  - "cn=users,dc=example,dc=com"
    #  - "cn=admins,dc=example,dc=com"
    #  - "cn=John Doe,cn=other users,dc=example,dc=com"
  roles.yml: |
    # The default roles file is empty as the preferred method of defining roles is
  log4j2.properties: |
    status = error
    logger.action.name = org.elasticsearch.action
    logger.action.level = debug
    appender.rolling.type = Console
    appender.rolling.name = rolling
    appender.rolling.layout.type = ESJsonLayout
    appender.rolling.layout.type_name = server
    rootLogger.level = info
    rootLogger.appenderRef.rolling.ref = rolling
    appender.deprecation_rolling.type = Console
    appender.deprecation_rolling.name = deprecation_rolling
    appender.deprecation_rolling.layout.type = ESJsonLayout
    appender.deprecation_rolling.layout.type_name = deprecation
    logger.deprecation.name = org.elasticsearch.deprecation
    logger.deprecation.level = warn
    logger.deprecation.appenderRef.deprecation_rolling.ref = deprecation_rolling
    logger.deprecation.additivity = false
    appender.index_search_slowlog_rolling.type = Console
    appender.index_search_slowlog_rolling.name = index_search_slowlog_rolling
    appender.index_search_slowlog_rolling.layout.type = ESJsonLayout
    appender.index_search_slowlog_rolling.layout.type_name = index_search_slowlog
    logger.index_search_slowlog_rolling.name = index.search.slowlog
    logger.index_search_slowlog_rolling.level = trace
    logger.index_search_slowlog_rolling.appenderRef.index_search_slowlog_rolling.ref = index_search_slowlog_rolling
    logger.index_search_slowlog_rolling.additivity = false
    appender.index_indexing_slowlog_rolling.type = Console
    appender.index_indexing_slowlog_rolling.name = index_indexing_slowlog_rolling
    appender.index_indexing_slowlog_rolling.layout.type = ESJsonLayout
    appender.index_indexing_slowlog_rolling.layout.type_name = index_indexing_slowlog
    logger.index_indexing_slowlog.name = index.indexing.slowlog.index
    logger.index_indexing_slowlog.level = trace
    logger.index_indexing_slowlog.appenderRef.index_indexing_slowlog_rolling.ref = index_indexing_slowlog_rolling
    logger.index_indexing_slowlog.additivity = false
    appender.audit_rolling.type = Console
    appender.audit_rolling.name = audit_rolling
    appender.audit_rolling.layout.type = PatternLayout
    appender.audit_rolling.layout.pattern = {\
    "type": "audit", \
    "timestamp":"%d{yyyy-MM-dd'T'HH:mm:ss,SSSZ}"\
    %varsNotEmpty{, "node.name":"%enc{%map{node.name}}{JSON}"}\
    %varsNotEmpty{, "node.id":"%enc{%map{node.id}}{JSON}"}\
    %varsNotEmpty{, "host.name":"%enc{%map{host.name}}{JSON}"}\
    %varsNotEmpty{, "host.ip":"%enc{%map{host.ip}}{JSON}"}\
    %varsNotEmpty{, "event.type":"%enc{%map{event.type}}{JSON}"}\
    %varsNotEmpty{, "event.action":"%enc{%map{event.action}}{JSON}"}\
    %varsNotEmpty{, "user.name":"%enc{%map{user.name}}{JSON}"}\
    %varsNotEmpty{, "user.run_by.name":"%enc{%map{user.run_by.name}}{JSON}"}\
    %varsNotEmpty{, "user.run_as.name":"%enc{%map{user.run_as.name}}{JSON}"}\
    %varsNotEmpty{, "user.realm":"%enc{%map{user.realm}}{JSON}"}\
    %varsNotEmpty{, "user.run_by.realm":"%enc{%map{user.run_by.realm}}{JSON}"}\
    %varsNotEmpty{, "user.run_as.realm":"%enc{%map{user.run_as.realm}}{JSON}"}\
    %varsNotEmpty{, "user.roles":%map{user.roles}}\
    %varsNotEmpty{, "origin.type":"%enc{%map{origin.type}}{JSON}"}\
    %varsNotEmpty{, "origin.address":"%enc{%map{origin.address}}{JSON}"}\
    %varsNotEmpty{, "realm":"%enc{%map{realm}}{JSON}"}\
    %varsNotEmpty{, "url.path":"%enc{%map{url.path}}{JSON}"}\
    %varsNotEmpty{, "url.query":"%enc{%map{url.query}}{JSON}"}\
    %varsNotEmpty{, "request.method":"%enc{%map{request.method}}{JSON}"}\
    %varsNotEmpty{, "request.body":"%enc{%map{request.body}}{JSON}"}\
    %varsNotEmpty{, "request.id":"%enc{%map{request.id}}{JSON}"}\
    %varsNotEmpty{, "action":"%enc{%map{action}}{JSON}"}\
    %varsNotEmpty{, "request.name":"%enc{%map{request.name}}{JSON}"}\
    %varsNotEmpty{, "indices":%map{indices}}\
    %varsNotEmpty{, "opaque_id":"%enc{%map{opaque_id}}{JSON}"}\
    %varsNotEmpty{, "x_forwarded_for":"%enc{%map{x_forwarded_for}}{JSON}"}\
    %varsNotEmpty{, "transport.profile":"%enc{%map{transport.profile}}{JSON}"}\
    %varsNotEmpty{, "rule":"%enc{%map{rule}}{JSON}"}\
    %varsNotEmpty{, "event.category":"%enc{%map{event.category}}{JSON}"}\
    }%n
    logger.xpack_security_audit_logfile.name = org.elasticsearch.xpack.security.audit.logfile.LoggingAuditTrail
    logger.xpack_security_audit_logfile.level = info
    logger.xpack_security_audit_logfile.appenderRef.audit_rolling.ref = audit_rolling
    logger.xpack_security_audit_logfile.additivity = false
    logger.xmlsig.name = org.apache.xml.security.signature.XMLSignature
    logger.xmlsig.level = error
    logger.samlxml_decrypt.name = org.opensaml.xmlsec.encryption.support.Decrypter
    logger.samlxml_decrypt.level = fatal
    logger.saml2_decrypt.name = org.opensaml.saml.saml2.encryption.Decrypter
    logger.saml2_decrypt.level = fatal
  jvm.options: |
    -Xms1g
    -Xmx1g
    -XX:+UseConcMarkSweepGC
    -XX:CMSInitiatingOccupancyFraction=75
    -XX:+UseCMSInitiatingOccupancyOnly
    -Des.networkaddress.cache.ttl=60
    -Des.networkaddress.cache.negative.ttl=10
    -XX:+AlwaysPreTouch
    -Xss1m
    -Djava.awt.headless=true
    -Dfile.encoding=UTF-8
    -Djna.nosys=true
    -XX:-OmitStackTraceInFastThrow
    -Dio.netty.noUnsafe=true
    -Dio.netty.noKeySetOptimization=true
    -Dio.netty.recycler.maxCapacityPerThread=0
    -Dlog4j.shutdownHookEnabled=false
    -Dlog4j2.disable.jmx=true
    -Djava.io.tmpdir=${ES_TMPDIR}
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:HeapDumpPath=data
    -XX:ErrorFile=logs/hs_err_pid%p.log
    8:-XX:+PrintGCDetails
    8:-XX:+PrintGCDateStamps
    8:-XX:+PrintTenuringDistribution
    8:-XX:+PrintGCApplicationStoppedTime
    8:-Xloggc:logs/gc.log
    8:-XX:+UseGCLogFileRotation
    8:-XX:NumberOfGCLogFiles=32
    8:-XX:GCLogFileSize=64m
    9-:-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m
    9-:-Djava.locale.providers=COMPAT
kind: ConfigMap
metadata:
  namespace: log-mon
  creationTimestamp: null
  name: es-config
